travis:
  secure:
    BINSTAR_TOKEN: tYMkmNsz63RE+iPlzIbKDR95z+qyUhySWrU/jSEbmnVAbzzly0UBSni+DW9NsDHpR6lf/6dN1fXcVaEKkXqZZJf/h0Z383cC1EznKSeD8r3O2SEGo9QuSEavr9+/1fWCNx+keRXLnkWg8ZAnsjfyLahIhFOQatoijfJ7smA72115/PWzzlWLBL36u9oCQ0W10qA4cVNJ4p+KKkl1xJ3bAkqqd0p1LXDPQWaoLHXfcvveJP34xQ6+8cscakXq6e7MpRclRmPbYNe0y5ZFF4XmK2sP9VQZsrBtRNRfmRZn0AhNre7OMehPukWQbZHVoS7FEHv6dlcP3n+GwK4UTxIB0nkl92Qt6jwXp0bLqOB2caExuV5ofEtFF3fxSn/AmJViazAzz1ChlKYnOAHTQA4nKU9eEO7gWcmzTxxejHONvqRbACaVTVY/5yQKfI0pigu03SdfPPxnVA+XgwOwNn2AbWdLP2cN0fNFDlMrjyto0x6yFij1HMl0a4wJtSgVUXdjFzd7TI4pFh8wUiVYZtE7tY9Sv6Z38cS5R/VN3gaV03dRkgyRv3HEcXT/+Tjt8jmjcrnJiDU8vMqaDitd7yty8q/nroa47NryheU8mECqi4sNEPU8V28gTHAVYP5KJ2PGimZQWmy1j1Px3ReVzpJIpQHmCkLEu8Csc3k89yCUN+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
